[package]
name = "termion_ext"
version = "0.1.0"
authors = ["nicooffee <nicolas.honorato@usach.cl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"